### ISSUE TITLE
Can't open forms on Craft 3.5

### ISSUE THREAD

**Issue by Coysh** [solspace/craft-express-forms#38]
### Description
On opening the forms page, I get a `Call to a member function getIsLivePreview() on string` error.

Stacktrace below:
```
Error: Call to a member function getIsLivePreview() on string in /home/vagrant/sites/renovare/vendor/craftcms/cms/src/web/Controller.php:133
Stack trace:
#0 /home/vagrant/sites/renovare/vendor/yiisoft/yii2/base/Controller.php(178): craft\web\Controller->beforeAction(Object(yii\base\InlineAction))
#1 /home/vagrant/sites/renovare/vendor/craftcms/cms/src/web/Controller.php(181): yii\base\Controller->runAction('index', Array)
#2 /home/vagrant/sites/renovare/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('index', Array)
#3 /home/vagrant/sites/renovare/vendor/craftcms/cms/src/web/Application.php(295): yii\base\Module->runAction('express-forms/f...', Array)
#4 /home/vagrant/sites/renovare/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('express-forms/f...', Array)
#5 /home/vagrant/sites/renovare/vendor/craftcms/cms/src/web/Application.php(280): yii\web\Application->handleRequest(Object(craft\web\Request))
#6 /home/vagrant/sites/renovare/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#7 /home/vagrant/sites/renovare/public/index.php(17): yii\base\Application->run()
#8 {main}
```

### Additional info

- Express Forms edition & version: Latest
- Craft version: Craft CMS 3.5.0-RC3
- PHP version:  7.2
- Database driver & version: mySQL

**Comment by kjmartens** [comment]
This will be resolved in Express Forms 1.0.6, available today. :)
